name: Build and test Meteor app

on:
  push:
    branches: 
      - '*'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Meteor.js environment
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: "1.10.2"
      - working-directory: ./boggl
        run: meteor npm install
      - working-directory: ./boggl
        run: meteor npm run test
      - working-directory: ./boggl
        run: meteor npm run prettier-check
